# Site
title:              Alessandro Pagiaro
bio:                'Software & Web Developer'
description:        "Studente di Informatica presso l'Università di Pisa."
reading_time:       true
words_per_minute:   200
logo:               'assets/img/me.png'
background:         #'assets/img/placeholder-big.jpg' #Leave empty to use background-color
#background-color:   edit variables.scss to set background color
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             it_IT
url:                https://apagiaro.it
#url:                http://127.0.0.1:4000

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

#Homepage Background Setting
enableScrollBackground: true
scrollImage:        'assets/img/bg_nosfondo.png'
enableOverlay:      true #add overlay layer
addScrollOnPageList: true #enable scroll image in pages that show a list of post/projects
addScrollOnPostPage: false #enable scroll image in single post page
addScrollOnProjectPage: true #enable scroll image in single project page

# Comments
disqus_shortname:   alessandro308

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              alessandropagiaro@gmail.com
twitter:            alessandro308
#facebook:           alessandro308
github-url:         alessandro308
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:          alessandro-pagiaro-9a5a5496
skype:              alessandro_308
telegram:           alessandro308
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
google_ana:   UA-105829132-1

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-redirect-from

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, bozze, LICENSE, Rakefile]
